### PR TITLE
added a callback when showing tooltips to customize contents

### PR DESCRIPTION
**Pull request by timkock**
Added functionality to allow for an option to provide custom tooltip contents based on item data as such

``` js
cal.init({
    tooltip: true,
    onTooltip: function(date, nb) {
        return $filter('currency')(nb || 0, '€ ', 2);
    }
});
```

This example pertains to an integration with angular where the tooltip displays currency formatted data.

### CODE REVIEW

**Comment by wa0x6e** [comment]
Can you only leave the changes in src/cal-heatmap.js ? Other files will be built automatically on new version release

**Comment by oxisto** [comment]
Is there any update to this pull request? I would really appreciate this feature.

**Comment by timkock** [comment]
@wa0x6e, @oxisto will fix this today, lets see if new pull request gets accepted because it was submitted September 16 2015 and commented on March 2016...

**Comment by wa0x6e** [comment]
Merge into v4 branch

**Pull request closed without merging**
