### PR TITLE
Update to d3 v4

### PR DESCRIPTION
**Pull request by JonDum**
This is a WIP PR

I've so far updated the syntax of all the d3 calls that have changed. 

Some things seem wonky, like the tooltip positioning. Trying to determine if that's something in my specific application or changes in the d3 v4 code.

Welcome to help for this PR.

### CODE REVIEW

**Comment by manimis902** [comment]
Hey @JonDum I'd happy to help out on this PR.
We are planning to use this library, and d3 v4 support is blocking us. Let me know how I can contribute to this effort.

cc: @wa0x6e

**Comment by coxom** [comment]
@JonDum the issue with the tooltip was just because you removed the code in line 871 that created the tooltip before the calculations.
Other changes in d3 include the [Maps](https://github.com/d3/d3-collection/blob/master/README.md#maps) that needed changing from forEach to each.

@wa0x6e any plans to create the v4 branch?

**Comment by coxom** [comment]
@JonDum We forked and patched the latest version with your changes and a few more tweaks here: https://github.com/hypercharge-code/cal-heatmap/tree/d3-v4

Only tested our use case so far.

**Comment by wa0x6e** [comment]
Closed, as not relevant anymore, next version will move directly to latest v7

**Pull request closed without merging**
